### ISSUE TITLE
Media Query Breakpoint Testing

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#115] opened 2015-09-21 20:57 UTC
It would be nice to be able to launch a test in multiple browser windows that correspond to the various media query breakpoints in order to instantly invoke the corresponding media query tests.  We can do this manually by using [Device Mode and Mobile Emulation](https://developer.chrome.com/devtools/docs/device-mode), but that requires interaction.

Anyone know if perhaps [Browsersync](http://www.browsersync.io) or something else does this, and whether it would be acceptable to embed it in the SUIT tests?

**Comment by timkelty** [comment] 2015-09-22 02:38
That would be nice if we could do it directly with Browsersync.
If we went the screenshot route - we could probably do it with PhantomJS relatively easily.

Also - a related tool: http://breakpointtester.com/

**Comment by oleersoy** [comment] 2015-09-22 04:36
Wow - http://breakpointtester.com/ is exactly what I was thinking...I think.

So does the screenshot route mean show screenshots of PhantomJS renderings at viewport sizes that match the media query breakpoints?

Google also has:
https://developers.google.com/web/tools/starter-kit/

I posted an issue on the browsersync repository and asked whether it can give us something similar to what the breakpoint tester does:
https://github.com/BrowserSync/browser-sync/issues/838

**Comment by simonsmith** [comment] 2015-10-08 19:05
This feels like a duplicate of #114 

I'd be in favour of closing this and keeping discussion in one place

**Comment by oleersoy** [comment] 2015-10-08 21:58
The objective of https://github.com/suitcss/suit/issues/114 is to enable designers studying the tests to get up to speed as fast as possible on the CSS concept / effect that the CSS has.

The objective this issue would be to be able to rapidly verify the effect of the media queries on the visual rendering of the test by opening browsers with varying viewport sizes triggering the media queries.  In other words be able to verify the media queries in action with minimal effort.

It could be done with a button that triggers javascript to resize the browser at given timing intervals.  It can probably just be closed / deferred though.  I'm sure breakpoint issues will get caught by users.

**Comment by oleersoy** [comment] 2015-10-08 22:06
Just realized that Bootstrap does something similar here:
[Bootstrap Responsive Utilities](http://v4-alpha.getbootstrap.com/layout/responsive-utilities/)

Except they just tell you do resize your browser to to trigger the queries.

**Comment by oleersoy** [comment] 2015-10-08 23:45
Actually this would probably best be handled by something like:
https://addons.mozilla.org/en-us/firefox/addon/emuflex/

Feel free to close.

**Comment by simonsmith** [comment] 2015-10-09 14:19
I'm planning to implement automated CSS testing on some static components for a work project. If it goes well we can look at bringing something like that into SUIT for testing components.

Something like https://github.com/garris/BackstopJS

**Closed by simonsmith** 2015-10-09 14:19 UTC

**Comment by oleersoy** [comment] 2015-10-09 15:35
Wow - That's pretty intriguing.  I'll have a closer look as well.
